# swagger配置
swagger:
  # 是否启用swagger，默认：true
  enabled: true
  # 标题
  title: "spring-data-jpa-demo"
  contact:
    # 维护人
    name: "gaohanghang"
    email: "1341947277@qq.com"
    url: "http://ghang.top"
  # 版本
  version: "1.0"
  # 描述
  description: "API 描述"
  # swagger扫描的基础包，默认：全扫描
  base-package: "org"
  # 需要处理的基础URL规则，默认：/**
  base-path: /**
  # 需要排除的URL规则，默认：空
  #  exclude-path: ""
  license: "Apache License, Version 2.0"
  license-url: "https://www.apache.org/licenses/LICENSE-2.0.html"

quartz:
  enabled: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/jpa-demo
    username: root
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update # update更新表结构，如果不存在则创建
    show-sql: true # 打印Sql
